### ISSUE TITLE
SFTP Permission denied (password).

### ISSUE THREAD

**Issue by kelegele** [wlixcc/SFTP-Deploy-Action#10]
Run wlixcc/SFTP-Deploy-Action@v1.0:

sftp start
Warning: Permanently added '**IP**' (ECDSA) to the list of known hosts.
root@IP: Permission denied (password).
Connection closed

**Comment by wlixcc** [comment]
this action use AuthorizedKeysFile， you should create ssh key pair and config your ssh server, then use private key connect your ssh server
