### ISSUE TITLE
Permission denied (publickey,password).

### ISSUE THREAD

**Issue by huiminxu** [wlixcc/SFTP-Deploy-Action#18]
![image](https://user-images.githubusercontent.com/33274229/122499485-99574c00-d023-11eb-9894-4abae67ae000.png)

**Comment by LubricantJam** [comment]
Getting the same issue also.

**Comment by zhypower1997** [comment]
同样遇到问题

**Comment by ManfredHu** [comment]
+1 最近是怎么了？

**Comment by zhypower1997** [comment]
这个解决方法，是重新配置ssh-key

**Comment by johanazhu** [comment]
+1

**Comment by zhenyuWang** [comment]
+1

**Comment by gabcvit** [comment]
I was facing the same error until I found the following page which solved my issue: https://zellwk.com/blog/github-actions-deploy/

In the end I had to regenerate an SSH key using:
`ssh-keygen -t rsa -b 4096 -C "your_email@example.com"` 

Previously I had created my key following the [recommendation by GitHub](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)
`ssh-keygen -t ed25519 -C "your_email@example.com"`

But the Ed25519 public-key algorithm seems to have caused some level of incompatibility either on my VPS or in this repo.

**Comment by zhenyuWang** [comment]
I solved this problem by following this article https://juejin.cn/post/7000655659758780453

**Comment by xiaochuntu** [comment]
put the server's pub key into authorized_keys can solve this problem
cat id_rsa.pub >> authorized_keys

**Comment by raazon** [comment]
> I solved this problem by following this article https://juejin.cn/post/7000655659758780453

This one really work fine. Thanks @zhenyuWang

**Comment by moazam1** [comment]
> 

It worked for me. You are lifesaver.

**Comment by wlixcc** [comment]
If you use the Ed25519 algorithm to generate an SSH key pair `ssh-keygen -t ed25519 -C "your_email@example.com"`, 
you need to note that the last line of the private key is a blank line. You need to retain it when adding Repository secrets, otherwise it may lead to an 'invalid format' error.

![image](https://github.com/wlixcc/SFTP-Deploy-Action/assets/15813435/e3a31536-8c8d-454e-8c2f-9a1e905a3534)

**Comment by wlixcc** [comment]
If the issue still exists, please reply under this issue and I will reopen it.
