### ISSUE TITLE
用create-react-app build之后会生成 static 文件，但是不能推进服务器中

### ISSUE THREAD

**Issue by johanazhu** [wlixcc/SFTP-Deploy-Action#22]
报错信息
Couldn't canonicalize: No such file or directory
Unable to canonicalize path "/home/johan/www/react-app/static"

配置如下
![image](https://user-images.githubusercontent.com/24203037/130002159-d6ad9925-dc3f-4827-b29e-bb646926d600.png)

**Comment by johanazhu** [comment]
> 报错信息
> Couldn't canonicalize: No such file or directory
> Unable to canonicalize path "/home/johan/www/react-app/static"
> 
> 配置如下
> ![image](https://user-images.githubusercontent.com/24203037/130002159-d6ad9925-dc3f-4827-b29e-bb646926d600.png)

我的解决方案很土，去服务器中 react-app 项目中新建一个 static 文件，供 sftp 写入

**Comment by LivioMirandaJr** [comment]
I'm getting the same error, any option other than creating the folder manually? My project is constantly generating new folders.
