### ISSUE TITLE
how to pass private key "passphrase"?

### ISSUE THREAD

**Issue by yazer79** [wlixcc/SFTP-Deploy-Action#23]
how to pass private key "passphrase" please?

**Comment by wlixcc** [comment]
Is this what you need？
https://serverfault.com/questions/466683/can-an-ssl-certificate-be-on-a-single-line-in-a-file-no-line-breaks
`awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}'  ca.pem`
