### ISSUE TITLE
Why is key required?

### ISSUE THREAD

**Issue by pboling** [wlixcc/SFTP-Deploy-Action#28]
Why can't we use usename and password, as standard SSH?

**Comment by zax71** [comment]
I can agree with this, for my use case i cannot use a public/priviate key pair

**Comment by wlixcc** [comment]
v1.2.4 support password  🎉

**Comment by infeo** [comment]
@wlixcc Albeit the README states that `ssh_private_key` is not required, looking at the action definition for version 1.25 it is still a requirement:
https://github.com/wlixcc/SFTP-Deploy-Action/blob/896dcfc555b4cbe36a4acc9bc0827ab474d429fc/action.yml#L15-L17

Should the input be left empty if a keypair is not used?
