### ISSUE TITLE
exec request failed on channel 0

### ISSUE THREAD

**Issue by DEPSTRCZ** [wlixcc/SFTP-Deploy-Action#48]
My deploy action ends with: 
`exec request failed on channel 0`
Log:
![image](https://user-images.githubusercontent.com/77269898/205913651-4d6bef33-d050-41b3-b7c6-8e0ad24159cd.png)

My action:
![image](https://user-images.githubusercontent.com/77269898/205913922-de783c6e-0c03-4507-a529-7b7a35c8df3a.png)

With WinSCP i can login just fine
Any idea what can that be?

**Comment by Xgabi86** [comment]
I have the same problem

**Comment by guillaumearnx** [comment]
idem

**Comment by wlixcc** [comment]
You can check the problem based on the gpt's answer

1.Permissions Issue: Ensure that the user account you are using to connect to the SFTP server has the necessary permissions to execute the commands you are attempting. Check both filesystem permissions and any SFTP server-specific restrictions.

2.Subsystem Configuration: Verify that the SFTP subsystem is correctly configured in the SSH server configuration file (sshd_config). Look for the line that starts with Subsystem sftp and make sure it points to the correct SFTP server binary, usually something like /usr/lib/openssh/sftp-server or /usr/libexec/openssh/sftp-server.

3.SSH Configuration Restrictions: Check if there are any command restrictions applied in the SSH configuration for specific users or groups (often found in sshd_config). For example, Match User or Match Group directives can restrict commands.

4.Shell Access: If your SFTP server requires shell access for executing certain commands, ensure that the user's shell is not set to a non-interactive or restricted shell in the /etc/passwd file.

5.Debugging SSH: To get more detailed information about what's going wrong, you can increase the verbosity of the SSH connection. Connect using the -vvv option with SSH to see detailed debug information:
