### ISSUE TITLE
`delete_remote_files` removes the entire folder, not "all files in the remote path" as documented

### ISSUE THREAD

**Issue by kb173** [wlixcc/SFTP-Deploy-Action#51]
The README says about `delete_remote_files`:

> Set `true` will delete all files in the remote path before upload.

However, this is not quite accurate: it deletes _the entire remote path_ rather than all files in it.

[The line in entrypoint.sh](https://github.com/wlixcc/SFTP-Deploy-Action/blob/master/entrypoint.sh#L22) calls `rm -rf $6`, but based on the documentation, I would expect `rm -rf $6/*`.

This is problematic in cases where permissions are only granted for that specific folder in the remote path - the folder cannot be recreated after deleting it.

I think the call should either be changed to `rm -rf $6/*`, or the documentation needs to be updated.

**Comment by wlixcc** [comment]
Thanks for your reminding, I will update the document
