### ISSUE TITLE
Source IP - Connection timed out

### ISSUE THREAD

**Issue by diegoarndt** [wlixcc/SFTP-Deploy-Action#6]
Hello there, 

I just created the action on my project and configured everything over there, but unfortunately I'm getting a message like this into the 'deploy file' section> **ssh: connect to host ec2-MYIP.us-east-2.compute.amazonaws.com port 22: Operation timed out**

![image](https://user-images.githubusercontent.com/26179059/91625726-27245680-e980-11ea-8288-63c6b6843f21.png)

Good thing is that I know what's happening. I have to allow as an Inbound Rule the following:

Type: SSH / Protocol: TCP / Post range: 22 / Source: ::/0;

![image](https://user-images.githubusercontent.com/26179059/91625645-58e8ed80-e97f-11ea-9126-dad4ee1aaaaa.png)

As you can see below, it works fine when not specifying the source...
![image](https://user-images.githubusercontent.com/26179059/91625768-6a7ec500-e980-11ea-9580-328d0470466e.png)

But obviously I don't want to do that for security reasons, so I need to find out the source I need to put there.
I've tried a lot of Github IP addresses already, but all of them were unsuccessful.

Does anyone here know what's the right source for it to work in a protected way?

Thanks in advance.

**Comment by wlixcc** [comment]
> sftp -b $TEMP_SFTP_FILE -P $3 $7 -o **StrictHostKeyChecking=no** -i $TEMP_SSH_PRIVATE_KEY_FILE $1@$2

When using sftp to connect to your server from the github server, for verification convenience, use **StrictHostKeyChecking=no** caused this problem
