### ISSUE TITLE
传输文件是增量更新，有清空文件夹的配置么

### ISSUE THREAD

**Issue by Saszr** [wlixcc/SFTP-Deploy-Action#7]
打包部署的话，之前旧的文件还是保留的

**Comment by wlixcc** [comment]
目前暂时没有, 可以配合其他命令实现删除文件内容的功能哈

**Comment by CrabAss** [comment]
@wlixcc 您好，能否大概说明一下如何配合其他命令实现删除文件内容的功能？谢谢

**Comment by wlixcc** [comment]
@CrabAss 通过命令行登录服务端,对应路径下执行rm, 也可以看看目前github上有没有对应的action可以删除服务端的文件
