### ISSUE TITLE
Option to force create non-existing output folder

### ISSUE THREAD

**Issue by ChrisAnkowski** [wlixcc/SFTP-Deploy-Action#9]
Hey,
I try to upload my build to a non-existing output folder.
Unfortunately it seems this is not supported. Any way I could accomplish that?
`sftp upload error!  Error: Remote Error: No such directory`

**Comment by wlixcc** [comment]
version 1.1 support create direcotry #4 , If there are still problems, reopen this issue

**Comment by ctrlmaniac** [comment]
I have a problem with this option. I'm using delete_remote_files and it indeed deletes all files BUT since I'm copying files into a subdirectory, this subdirectory get deleted. By deleting the folder the action fail because it cannot find the subfolder! How can I recreate that subfolder?
